In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor

In [2]:
df = pd.read_csv(r"C:\Users\Anushkha Bhagra\Downloads\ML\regression\StudentPerformanceFactors.csv")
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [3]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [4]:
df["Teacher_Quality"] = df["Teacher_Quality"].fillna(df["Teacher_Quality"].mode()[0])
df["Parental_Education_Level"] = df["Parental_Education_Level"].fillna(df["Parental_Education_Level"].mode()[0])
df["Distance_from_Home"] = df["Distance_from_Home"].fillna(df["Distance_from_Home"].mode()[0])

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
#encoding:
label = LabelEncoder()
df["encoded_parent"] = label.fit_transform(df["Parental_Involvement"]) 
var1 = dict(zip(df["Parental_Involvement"],df["encoded_parent"]))
print(var1)

df["encoded_resource"] = label.fit_transform(df["Access_to_Resources"]) 
var2 = dict(zip(df["Access_to_Resources"],df["encoded_resource"]))
print(var2)

df["encoded_activities"] = label.fit_transform(df["Extracurricular_Activities"]) 
var3 = dict(zip(df["Extracurricular_Activities"],df["encoded_activities"]))
print(var3)

df["encoded_learning"] = label.fit_transform(df["Learning_Disabilities"]) 
var4 = dict(zip(df["Learning_Disabilities"],df["encoded_learning"]))
print(var4)

df["encoded_edu"] = label.fit_transform(df["Parental_Education_Level"]) 
var5 = dict(zip(df["Parental_Education_Level"],df["encoded_edu"]))
print(var5)

df["encoded_motivation"] = label.fit_transform(df["Motivation_Level"]) 
var6 = dict(zip(df["Motivation_Level"],df["encoded_motivation"]))
print(var6)

df["encoded_internet"] = label.fit_transform(df["Internet_Access"]) 
var7 = dict(zip(df["Internet_Access"],df["encoded_internet"]))
print(var7)

df["encoded_home"] = label.fit_transform(df["Distance_from_Home"]) 
var8 = dict(zip(df["Distance_from_Home"],df["encoded_home"]))
print(var8)


df["encoded_income"] = label.fit_transform(df["Family_Income"]) 
var9 = dict(zip(df["Family_Income"],df["encoded_income"]))
print(var9)


df["encoded_teacher"] = label.fit_transform(df["Teacher_Quality"]) 
var10 = dict(zip(df["Teacher_Quality"],df["encoded_teacher"]))
print(var10)

df["encoded_school"] = label.fit_transform(df["School_Type"]) 
var11 = dict(zip(df["School_Type"],df["encoded_school"]))
print(var11)

df["encoded_peer"] = label.fit_transform(df["Peer_Influence"]) 
var12 = dict(zip(df["Peer_Influence"],df["encoded_peer"]))
print(var12)

df["encoded_gender"] = label.fit_transform(df["Gender"]) 
var13 = dict(zip(df["Gender"],df["encoded_gender"]))
print(var13)

{'Low': 1, 'Medium': 2, 'High': 0}
{'High': 0, 'Medium': 2, 'Low': 1}
{'No': 0, 'Yes': 1}
{'No': 0, 'Yes': 1}
{'High School': 1, 'College': 0, 'Postgraduate': 2}
{'Low': 1, 'Medium': 2, 'High': 0}
{'Yes': 1, 'No': 0}
{'Near': 2, 'Moderate': 1, 'Far': 0}
{'Low': 1, 'Medium': 2, 'High': 0}
{'Medium': 2, 'High': 0, 'Low': 1}
{'Public': 1, 'Private': 0}
{'Positive': 2, 'Negative': 0, 'Neutral': 1}
{'Male': 1, 'Female': 0}

In [7]:
df.drop(columns=["Parental_Involvement","Access_to_Resources","Extracurricular_Activities","Motivation_Level","Internet_Access","Family_Income","Teacher_Quality","School_Type","Peer_Influence","Learning_Disabilities","Parental_Education_Level"	,"Distance_from_Home","Gender"],inplace=True)

In [8]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score,encoded_parent,encoded_resource,encoded_activities,encoded_learning,encoded_edu,encoded_motivation,encoded_internet,encoded_home,encoded_income,encoded_teacher,encoded_school,encoded_peer,encoded_gender
0,23,84,7,73,0,3,67,1,0,0,0,1,1,1,2,1,2,1,2,1
1,19,64,8,59,2,4,61,1,2,0,0,0,1,1,1,2,2,1,0,0
2,24,98,7,91,2,4,74,2,2,1,0,2,2,1,2,2,2,1,1,1
3,29,89,8,98,1,4,71,1,2,1,0,1,2,1,1,2,2,1,0,1
4,19,92,6,65,3,4,70,2,2,1,0,0,2,1,2,2,0,1,1,0

In [9]:
#feature selection:
x = df.drop(columns=["Exam_Score"])
y = df["Exam_Score"]

In [10]:
#data splitting:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
#hyper parameter:
para_grid = {"max_depth": [3,5,7,8,9,11],
            "n_estimators": [100,150,200,250,300,350]}

In [12]:
#tunning:
tunning = RandomForestRegressor(random_state=42)

In [13]:
grid_model = GridSearchCV(param_grid= para_grid,
                          cv = 5,
                          n_jobs=-1,
                          scoring = "r2",
                          estimator = tunning)
grid_model.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 8, 9, 11],
                         'n_estimators': [100, 150, 200, 250, 300, 350]},
             scoring='r2')

In [14]:
grid_model.best_params_

{'max_depth': 11, 'n_estimators': 250}

In [15]:
model = grid_model.best_estimator_

In [16]:
y_pred = model.predict(x_test)
r2_score(y_test,y_pred)

0.6506448433052088

In [17]:
y_pred_train = model.predict(x_train)
r2_score(y_train,y_pred_train)

0.9266568960913287

In [19]:
#predictive model:
#Hours_Studied	Attendance	Parental_Involvement	Access_to_Resources	Extracurricular_Activities	Sleep_Hours	Previous_Scores	Motivation_Level	Internet_Access	Tutoring_Sessions	Family_Income	Teacher_Quality	School_Type	Peer_Influence	Physical_Activity	Learning_Disabilities	Parental_Education_Level	Distance_from_Home	Gender	
hours_study = int(input("enter the hours studied"))
attendance = int(input("enter your attendance"))
parental_invol = int(input("enter your parental involvemnet -->{'Low': 1, 'Medium': 2, 'High': 0}"))
resoures_access = int(input("enter your access to resources -->{'High': 0, 'Medium': 2, 'Low': 1}"))
extra_activity = int(input("enter your extracirculat activity -->{'No': 0, 'Yes': 1}"))
sleep = int(input("enter number of hours you sleep"))
prev_score = int(input("enter your score"))
motivation = int(input("enter your motivation level-->{'Low': 1, 'Medium': 2, 'High': 0}"))
internet = int(input("enter your internet access-->{'Yes': 1, 'No': 0}"))
tutor = int(input("enter yout tutoring session -->"))
family_income = int(input("enter your family income-->{'Low': 1, 'Medium': 2, 'High': 0}"))
teacher = int(input("enter your teaher quality-->{'Medium': 2, 'High': 0, 'Low': 1}"))
school = int(input("enter yor school type-->{'Public': 1, 'Private': 0}"))
peer = int(input("enter your peer influence -- >{'Positive': 2, 'Negative': 0, 'Neutral': 1}"))
phy_activity = int(input("enter your physical activity"))
learn_dis = int(input("enter learning disabilities-->{'No': 0, 'Yes': 1}"))
parental_edu = int(input("enter your parents education-->{'High School': 1, 'College': 0, 'Postgraduate': 2}"))
home_dis = int(input("enter your distance from home-->{'Near': 2, 'Moderate': 1, 'Far': 0}"))
gender = int(input("enter your gender-->{'Male': 1, 'Female': 0}"))
data = model.predict([[hours_study,attendance, parental_invol,resoures_access,extra_activity,sleep,prev_score,motivation,internet,tutor,family_income,teacher,school,peer,phy_activity,learn_dis,parental_edu,home_dis,gender]])
print("score of the student is:", data)

enter the hours studied 4
enter your attendance 90
enter your parental involvemnet -->{'Low': 1, 'Medium': 2, 'High': 0} 0
enter your access to resources -->{'High': 0, 'Medium': 2, 'Low': 1} 0
enter your extracirculat activity -->{'No': 0, 'Yes': 1} 1
enter number of hours you sleep 9
enter your score 90
enter your motivation level-->{'Low': 1, 'Medium': 2, 'High': 0} 0
enter your internet access-->{'Yes': 1, 'No': 0} 1
enter yout tutoring session --> 4
enter your family income-->{'Low': 1, 'Medium': 2, 'High': 0} 0
enter your teaher quality-->{'Medium': 2, 'High': 0, 'Low': 1} 0
enter yor school type-->{'Public': 1, 'Private': 0} 0
enter your peer influence -- >{'Positive': 2, 'Negative': 0, 'Neutral': 1} 2
enter your physical activity 3
enter learning disabilities-->{'No': 0, 'Yes': 1} 0
enter your parents education-->{'High School': 1, 'College': 0, 'Postgraduate': 2} 0
enter your distance from home-->{'Near': 2, 'Moderate': 1, 'Far': 0} 2
enter your gender-->{'Male': 1, 'Female': 0} 0

score of the student is: [65.26757347]

E:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(